Repository Final-Project-Team11/Meer_catlender_FE, pull requests merged in 2023-05, with the labels that each got.

#198 Features/hot fix
  src/components/Atoms/Button/style.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/pages/Business/components/DetailUser.tsx
  src/pages/Business/components/ViewUser.tsx
  src/pages/Login/components/AdminLoginForm.tsx
  src/pages/Login/styles.ts
  src/pages/MasterSignup/components/SignupForm.tsx
Labels: bug🐛

#199 [!HOTFIX] : 💥 저장된 파일 클릭시 새창으로 띄우도록 수정
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
Labels: bug🐛

#200 [!HOTFIX] : 💥
  src/components/Atoms/Button/style.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/pages/Business/components/DetailUser.tsx
  src/pages/Business/components/ViewUser.tsx
  src/pages/Login/components/AdminLoginForm.tsx
  src/pages/Login/styles.ts
  src/pages/MasterSignup/components/SignupForm.tsx
Labels: bug🐛

#202 Features/hot fix
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/usePostVacation.ts
  src/api/hooks/Main/usePostschedule.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/pages/Main/Main.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/interfaces.ts
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/states/recoilSelectedDateState.ts
Labels: bug🐛

#203 HOTFIX : 💥 월별 이동 가능/ Logout 추가/
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/usePostVacation.ts
  src/api/hooks/Main/usePostschedule.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/pages/Main/Main.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/interfaces.ts
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/states/recoilSelectedDateState.ts
Labels: bug🐛

#204 HOTFIX / 내가올린파일 디테일 문제 수정
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/interfaces.ts
Labels: bug🐛

#206 Features/catch bug
  src/api/hooks/Main/usePostVacation.ts
  src/api/hooks/Main/usePostschedule.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/utils.ts
Labels: bug🐛

#207 Dev
  src/api/hooks/Main/usePostVacation.ts
  src/api/hooks/Main/usePostschedule.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/utils.ts
Labels: bug🐛

#210 Refactoring/card components
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/style.ts
  src/components/Card/Card.tsx
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/style.ts
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/hooks/common/useInfiniteQueryHook.ts
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SubMain/Header/Header.tsx
Labels: features⚙️, style🎨, RE-FACTORING♻️

#211 Dev
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/style.ts
  src/components/Card/Card.tsx
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/style.ts
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/hooks/common/useInfiniteQueryHook.ts
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/SubMain/Header/Header.tsx
Labels: features⚙️, style🎨, RE-FACTORING♻️

#212 Featrues/business page
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Dropdown/styles.ts
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/style.ts
  src/pages/Business/Business.tsx
  src/pages/Business/components/CreateUser.tsx
  src/pages/Business/components/DetailUser.tsx
  src/pages/Business/components/ViewUser.tsx
  src/pages/Business/hooks/useGetUser.ts
  src/pages/Business/hooks/usePatchUser.ts
  src/pages/Business/hooks/useSignup.ts
  src/pages/Business/hooks/useUserIdValidation.ts
  src/pages/Business/styles.ts
Labels: features⚙️, RE-FACTORING♻️

#215 Refactoring/mypage managerpage
  src/api/hooks/Card/useGetCardDetail.ts
  src/api/hooks/Card/useGetCardInfo.ts
  src/api/hooks/Feed/useGetFeed.ts
  src/api/hooks/Feed/usePatchFeed.ts
  src/api/hooks/UploadedFile/useGetUploadedDetail.ts
  src/assets/Icons/CalendarIcon.tsx
  src/assets/Icons/TagIconTitle.tsx
  src/components/Card/Card.tsx
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/style.ts
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/style.ts
  src/components/Feed/interfaces.ts
  src/components/RequestList/Request.tsx
  src/components/Tag/Tag.tsx
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/components/UploadedFileTab/interfaces.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
Labels: features⚙️, style🎨, RE-FACTORING♻️

#216 Dev
  src/api/hooks/Card/useGetCardDetail.ts
  src/api/hooks/Card/useGetCardInfo.ts
  src/api/hooks/Feed/useGetFeed.ts
  src/api/hooks/Feed/usePatchFeed.ts
  src/api/hooks/UploadedFile/useGetUploadedDetail.ts
  src/assets/Icons/CalendarIcon.tsx
  src/assets/Icons/TagIconTitle.tsx
  src/components/Card/Card.tsx
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/style.ts
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/style.ts
  src/components/Feed/interfaces.ts
  src/components/RequestList/Request.tsx
  src/components/Tag/Tag.tsx
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/components/UploadedFileTab/interfaces.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
Labels: features⚙️, style🎨, RE-FACTORING♻️

#217 유저 피드백에 관련 내용 수정.
  src/api/hooks/Main/usePostschedule.ts
  src/assets/Icons/HeaderLogo.tsx
  src/assets/Icons/TodayMoveIcon.tsx
  src/assets/Meerkat/ChangeSchedule.tsx
  src/assets/Meerkat/ChangeVacation.tsx
  src/components/Atoms/Dropdown/styles.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/Writing/Writing.tsx
  src/components/Main/DocumentForm/commonStyles.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/styles.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/subMain.css
  src/pages/SubMain/theme.ts
Labels: bug🐛, features⚙️, style🎨, fix🔧

#218 Main Page 유저 피드백 적용
  src/api/hooks/Main/usePostschedule.ts
  src/assets/Icons/HeaderLogo.tsx
  src/assets/Icons/TodayMoveIcon.tsx
  src/assets/Meerkat/ChangeSchedule.tsx
  src/assets/Meerkat/ChangeVacation.tsx
  src/components/Atoms/Dropdown/styles.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/Writing/Writing.tsx
  src/components/Main/DocumentForm/commonStyles.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/styles.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/subMain.css
  src/pages/SubMain/theme.ts
Labels: bug🐛, features⚙️, style🎨, fix🔧

#220 Card-Detail 디자인 전체 수정
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/style.ts
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/style.ts
Labels: style🎨

#219 home, login-page 디자인 수정
  public/favicon_meer.ico
  src/assets/Icons/HeaderLogo.tsx
  src/assets/Meerkat/ManagerHead.tsx
  src/assets/Meerkat/MeerkatHead4.tsx
  src/assets/Meerkat/UserHead.tsx
  src/assets/images/NotFound.jpg
  src/assets/images/home/logo.png
  src/assets/images/home/main1.jpg
  src/assets/images/home/main2.jpg
  src/assets/images/home/main3.jpg
  src/assets/images/home/main4.jpg
  src/assets/images/home/main5.jpg
  src/assets/images/home/main6.jpg
  src/pages/Home/Home.tsx
  src/pages/Home/home.css
  src/pages/Home/styles.ts
  src/pages/Login/Login.tsx
  src/pages/Login/styles.ts
  src/styles/colors.ts
Labels: style🎨

#221 UT 피드백 반영을 위한 main 최신화
  public/favicon_meer.ico
  src/assets/Icons/HeaderLogo.tsx
  src/assets/Meerkat/ManagerHead.tsx
  src/assets/Meerkat/MeerkatHead4.tsx
  src/assets/Meerkat/UserHead.tsx
  src/assets/images/NotFound.jpg
  src/assets/images/home/logo.png
  src/assets/images/home/main1.jpg
  src/assets/images/home/main2.jpg
  src/assets/images/home/main3.jpg
  src/assets/images/home/main4.jpg
  src/assets/images/home/main5.jpg
  src/assets/images/home/main6.jpg
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/style.ts
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/style.ts
  src/pages/Home/Home.tsx
  src/pages/Home/home.css
  src/pages/Home/styles.ts
  src/pages/Login/Login.tsx
  src/pages/Login/styles.ts
  src/styles/colors.ts
Labels: features⚙️, style🎨, deploy🚀

#222 UT 피드백 반영을 위한 main 최신화
  src/components/Atoms/Button/style.ts
  src/pages/SubMain/Header/Header.tsx
Labels: deploy🚀

#224 UT 피드백을 반영한 Signup-page Update
  src/assets/Icons/HomeLogo.tsx
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/pages/Business/Business.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/components/AdminLoginForm.tsx
  src/pages/Login/components/UserLoginForm.tsx
  src/pages/Login/hooks/useLogin.ts
  src/pages/Login/styles.ts
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/MasterSignup/hooks/DaumAddressAPI.tsx
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
  src/pages/MasterSignup/hooks/useCompanyNumCheck.ts
  src/pages/MasterSignup/styles.ts
Labels: bug🐛, fix🔧, RE-FACTORING♻️

#225 UT 피드백 반영을 위한 main 최신화
  src/assets/Icons/HomeLogo.tsx
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/pages/Business/Business.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/components/AdminLoginForm.tsx
  src/pages/Login/components/UserLoginForm.tsx
  src/pages/Login/hooks/useLogin.ts
  src/pages/Login/styles.ts
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/MasterSignup/hooks/DaumAddressAPI.tsx
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
  src/pages/MasterSignup/hooks/useCompanyNumCheck.ts
  src/pages/MasterSignup/styles.ts
Labels: deploy🚀

#228 Features/retactoring main
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/usePostschedule.ts
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonStyles.ts
  src/components/Main/DocumentForm/components/DatePicker/DatePickerComponent.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/ReadMe.text
  src/hooks/Readme.text
  src/hooks/temp.tsx
  src/hooks/useFilterData.ts
  src/pages/Main/Main.tsx
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodaySchedules/TodaySchedules.tsx
  src/pages/SubMain/TodaySchedules/index.ts
  src/pages/SubMain/TodaySchedules/interfaces.ts
  src/pages/SubMain/TodaySchedules/styles.ts
  src/pages/SubMain/interfaces.ts
  src/pages/SubMain/styles.ts
  src/pages/SubMain/utils.ts
Labels: bug🐛, style🎨, RE-FACTORING♻️

#229 Main Refactoring & 디자인 변경
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/usePostschedule.ts
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonStyles.ts
  src/components/Main/DocumentForm/components/DatePicker/DatePickerComponent.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/ReadMe.text
  src/hooks/Readme.text
  src/hooks/temp.tsx
  src/hooks/useFilterData.ts
  src/pages/Main/Main.tsx
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodaySchedules/TodaySchedules.tsx
  src/pages/SubMain/TodaySchedules/index.ts
  src/pages/SubMain/TodaySchedules/interfaces.ts
  src/pages/SubMain/TodaySchedules/styles.ts
  src/pages/SubMain/interfaces.ts
  src/pages/SubMain/styles.ts
  src/pages/SubMain/utils.ts
Labels: bug🐛, features⚙️, style🎨

#230 [REFACTOR] : ♻️ DropDown hooks 분리 및 resize 고려
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/hooks/common/useDropDown.ts
Labels: RE-FACTORING♻️

#232 Refactoring/user feedback
  src/api/hooks/Vacation/usePutDecision.ts
  src/components/Card/Card.tsx
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/style.ts
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/style.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/style.ts
  src/components/RequestList/RequestDetail/RequestDetail.tsx
  src/components/VacationTab/Vacation/Vacation.tsx
  src/components/VacationTab/interfaces.ts
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/styles.ts
  src/pages/SubMain/Header/Header.tsx
Labels: features⚙️, style🎨, RE-FACTORING♻️

#237 마이페이지 메인페이지 사이즈 통일
  src/components/Board/style.ts
  src/components/Card/style.ts
  src/components/OneWeekCalendar/OneWeekCalendar.tsx
  src/pages/Main/styles.ts
  src/pages/MyPage/styles.ts
Labels: style🎨

#239 로딩 스피너 추가
  src/assets/images/LoadingSpinner.gif
  src/components/Loading/Loading.tsx
Labels: features⚙️

#242 마이페이지 로딩스피너 추가
  src/api/hooks/MyRequest/useGetMyRequest.ts
  src/api/hooks/Request/useGetRequestDetail.ts
  src/api/hooks/Tag/useGetTag.ts
  src/api/hooks/UploadedFile/useGetFile.ts
  src/api/hooks/Vacation/useGetVacation.ts
  src/api/hooks/Vacation/useGetVacationStatus.ts
  src/components/Card/Card.tsx
  src/components/Card/style.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/style.ts
  src/components/Main/CustomCalendar/CustomCalendar.tsx
  src/components/Main/CustomCalendar/styles.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/MyRequest/MyRequestList/style.ts
  src/components/RequestList/Request.tsx
  src/components/RequestList/RequestDetail/RequestDetail.tsx
  src/components/RequestList/RequestDetail/style.ts
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/RequestList/RequestedOne/style.ts
  src/components/RequestList/interfaces.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/Tags/style.ts
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/UploadedDetail/style.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/style.ts
  src/components/VacationStatus/VacationStatus.tsx
  src/components/VacationStatus/style.ts
  src/components/VacationTab/Vacation/style.ts
  src/components/VacationTab/VacationTab.tsx
Labels: features⚙️, style🎨

#248 업로드된 파일 버그 수정
  src/api/hooks/UploadedFile/useGetUploadedDetail.ts
Labels: bug🐛

#249 Dev
  src/api/hooks/UploadedFile/useGetUploadedDetail.ts
Labels: bug🐛

#251 Features/retactoring last
  src/api/hooks/Main/usePostMeetingReport.ts
  src/api/hooks/Main/usePostReport.ts
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonInterface.ts
  src/components/Main/DocumentForm/commonStyles.ts
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/Main/Modal/ReportModal/styles.ts
  src/hooks/common/useDropDown.ts
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/SubMain.tsx
Labels: bug🐛, style🎨

#259 [My-Page] Card-Modify / 인풋값 자동변환
  src/api/hooks/Card/usePatchDetail.ts
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/style.ts
  src/components/Card/interfaces.ts
Labels: features⚙️, RE-FACTORING♻️

#261 Bugfix/card modify
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/pages/SubMain/SubMain.tsx
Labels: bug🐛

#265 [My-Page] Tag-Component / style 수정
  src/components/MyPage/Tag/Tag.tsx
  src/components/MyPage/Tag/Tags/Tags.tsx
Labels: style🎨

#266 [Deploy]
  src/components/MyPage/Tag/Tag.tsx
  src/components/MyPage/Tag/Tags/Tags.tsx
Labels: deploy🚀

#272 [Deploy]
  src/api/hooks/Main/usePostReport.ts
  src/components/Main/CustomCalendar/CustomCalendar.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/components/Main/DocumentForm/components/FileUpload/styles.ts
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/pages/Main/Main.tsx
  src/pages/SubMain/subMain.css
  src/pages/SubMain/theme.ts
Labels: deploy🚀

#273 Features/email certify
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/MasterSignup/hooks/useEmailValidation.ts
  src/pages/MasterSignup/hooks/useSendEmail.ts
Labels: features⚙️

#274 [Deploy]
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/MasterSignup/hooks/useEmailValidation.ts
  src/pages/MasterSignup/hooks/useSendEmail.ts
Labels: deploy🚀

#276 [Common] Components / DropDown Bug Fix
  package-lock.json
  src/components/Atoms/Dropdown/styles.ts
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/Main/Modal/ReportModal/interfaces.ts
  src/hooks/useFilterData.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodaySchedules/TodaySchedules.tsx
  src/states/recoilCalendarState.ts
  src/states/recoilReportState.ts
  tsconfig.json
Labels: bug🐛

#277 [Deploy]
  package-lock.json
  src/components/Atoms/Dropdown/styles.ts
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/Main/Modal/ReportModal/interfaces.ts
  src/hooks/useFilterData.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodaySchedules/TodaySchedules.tsx
  src/states/recoilCalendarState.ts
  src/states/recoilReportState.ts
  tsconfig.json
Labels: deploy🚀

#279 Features/event bubbing
  public/index.html
  src/components/Atoms/Dropdown/styles.ts
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
Labels: bug🐛

#280 [Deploy]
  public/index.html
  src/components/Atoms/Dropdown/styles.ts
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
Labels: bug🐛
