Repository Final-Project-Team11/Meer_catlender_FE, pull requests merged in 2023-04, with the labels that each got.

#9 Features/text area component
  src/components/TextArea/TextArea.tsx
  src/components/TextArea/index.ts
  src/components/TextArea/interfaces.ts
  src/components/TextArea/styles.ts
  yarn.lock
Labels: enhancement

#12 Features/tags component
  src/components/Feed/Category/style.ts
  src/components/Feed/Todo/style.ts
  src/components/Feed/style.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/Tags/Tags.tsx
  src/components/Tag/Tags/index.ts
  src/components/Tag/Tags/interfaces.ts
  src/components/Tag/Tags/style.ts
  src/components/Tag/index.ts
  src/components/Tag/interfaces.ts
  src/components/Tag/style.ts
  src/pages/MyPage/MyPage.tsx
Labels: enhancement

#26 Features/create calendar
  src/components/CustomCalendar/CustomCalendar.tsx
  src/components/CustomCalendar/Weekday/Weekday.tsx
  src/components/CustomCalendar/Weekday/index.ts
  src/components/CustomCalendar/Weekday/inferfaces.ts
  src/components/CustomCalendar/Weekday/styles.ts
  src/components/CustomCalendar/interfaces.ts
  src/components/CustomCalendar/styles.ts
  src/components/Feed/style.ts
  src/components/ToastCalendar/Calendar.tsx
  src/components/ToastCalendar/isEqual.ts
  src/pages/Main/Main.tsx
  src/pages/Main/index.ts
  src/pages/Main/main.css
  src/pages/Main/styles.ts
  src/pages/Main/theme.ts
  src/pages/Main/utils.ts
  src/shared/Router.tsx
Labels: enhancement

#34 Features/calendar header component
  src/components/Dropdown/DropdownBody/DropdownBody.tsx
  src/components/Dropdown/DropdownHeader/DropdownHeader.tsx
  src/components/Dropdown/DropdownHeader/index.ts
  src/components/Dropdown/DropdownHeader/interfaces.ts
  src/components/Dropdown/DropdownHeader/styles.ts
  src/pages/Main/Detail/Detail.tsx
  src/pages/Main/Detail/index.ts
  src/pages/Main/Detail/styles.ts
  src/pages/Main/Header/Header.tsx
  src/pages/Main/Header/index.ts
  src/pages/Main/Header/interfaces.ts
  src/pages/Main/Header/styles.ts
  src/pages/Main/Main.tsx
Labels: features

#39 [DESIGN] : 🎨 uploaded file component UI
  src/components/UploadedFileTab/FileCategory/Category.tsx
  src/components/UploadedFileTab/FileCategory/index.ts
  src/components/UploadedFileTab/FileCategory/interfaces.ts
  src/components/UploadedFileTab/FileCategory/style.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/style.ts
Labels: style

#40 Style/card component UI
  .gitignore
  package.json
  src/components/Card/Card.tsx
  src/components/Card/index.ts
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/pages/MyPage/MyPage.tsx
  yarn.lock
Labels: style

#43 Features/dropdown component
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/DropdownBody/DropdownBody.tsx
  src/components/Dropdown/DropdownBody/index.ts
  src/components/Dropdown/DropdownHeader/DropdownHeader.tsx
  src/components/Dropdown/DropdownHeader/index.ts
  src/components/Dropdown/DropdownHeader/interfaces.ts
  src/components/Dropdown/DropdownHeader/styles.ts
  src/components/Dropdown/index.ts
  src/components/Dropdown/interfaces.ts
  src/components/Dropdown/styles.ts
  src/pages/Login/Login.tsx
Labels: features

#47 Features/json server api test
  .gitignore
  src/api/hooks/useGetMain.ts
  src/api/utils/createQueryKey.ts
  src/pages/Main/Detail/Detail.tsx
  src/pages/Main/Header/Header.tsx
  src/pages/Main/Main.tsx
  src/pages/Main/main.css
Labels: bug

#53 Style/signup page UI
  src/pages/MasterSignup/MasterSignup.tsx
  src/pages/MasterSignup/styles.ts
Labels: style

#54 Features/vacation component css
  src/api/hooks/Vacation/useGetVacation.ts
  src/components/VacationTab/Vacation/Vacation.tsx
  src/components/VacationTab/Vacation/interfaces.ts
  src/components/VacationTab/Vacation/style.ts
  src/components/VacationTab/VacationTab.tsx
  src/components/VacationTab/interfaces.ts
Labels: style

#60 Style/feed component
  src/api/hooks/Feed/useGetFeed.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/interfaces.ts
  src/components/Feed/Category/style.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedTitle.tsx
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/interfaces.ts
  src/components/Feed/Todo/style.ts
  src/components/Feed/interfaces.ts
  src/components/Feed/style.ts
  src/components/VacationTab/VacationTab.tsx
Labels: style

#70 Features/add schedule ver2
  package.json
  src/App.tsx
  src/api/hooks/useGetMain.ts
  src/api/hooks/usePostschedule.ts
  src/auth/CookieUtils.ts
  src/axios/ReadMe.text
  src/axios/api.tsx
  src/components/Button/Button.tsx
  src/components/Button/interfaces.ts
  src/components/Button/styles.ts
  src/hooks/common/useTextarea.ts
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Detail/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/interfaces.ts
  src/pages/SubMain/subMain.css
  src/pages/SubMain/theme.ts
  src/pages/SubMain/utils.ts
  yarn.lock
Labels: features

#72 Features/feed component
  src/api/hooks/Feed/useCheckTodo.ts
  src/api/hooks/Feed/useDeleteCategory.ts
  src/api/hooks/Feed/useDeleteTodo.ts
  src/api/hooks/Feed/useGetFeed.ts
  src/api/hooks/Feed/usePostCategory.ts
  src/api/hooks/Feed/usePostTodo.ts
  src/api/utils/createQueryKey.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/interfaces.ts
  src/components/Feed/Category/style.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/interfaces.ts
  src/components/Feed/Todo/style.ts
  src/components/Feed/interfaces.ts
Labels: features

#77 [FIX] : 🐛 데이터가 없을 때 map에 대한 예외처리
  src/components/Feed/Feed.tsx
Labels: bug

#79 Features/report format
  src/components/VacationTab/VacationTab.tsx
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Detail/styles.ts
  src/pages/SubMain/SubMain.tsx
Labels: bug

#80 Features/tag component
  src/api/hooks/Feed/usePostTodo.ts
  src/api/hooks/Tag/useGetTag.ts
  src/api/hooks/Tag/usePatchTag.ts
  src/api/utils/createQueryKey.ts
  src/axios/api.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/style.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/Tags/Tags.tsx
  src/components/Tag/Tags/interfaces.ts
  src/components/Tag/Tags/style.ts
  src/components/Tag/interfaces.ts
  src/components/Tag/style.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/style.ts
  src/hooks/common/useInput.ts
  src/pages/MyPage/MyPage.tsx
Labels: features

#84 Feature/signup page
  package.json
  public/index.html
  src/components/Inputs/ButtonInput/ButtonInput.tsx
  src/components/Inputs/ButtonInput/interfaces.ts
  src/components/Inputs/Input/MaxInput.tsx
  src/components/Inputs/Input/interfaces.ts
  src/pages/Login/Login.tsx
  src/pages/MasterSignup/MasterSignup.tsx
  src/pages/MasterSignup/hooks/DaumAddressAPI.tsx
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
  src/pages/MasterSignup/hooks/usePasswordCheck.ts
  src/pages/MasterSignup/hooks/useSignup.ts
  src/pages/MasterSignup/interfaces.ts
  src/pages/MasterSignup/styles.ts
  yarn.lock
Labels: features

#85 Features/uploaded tab component
  src/api/hooks/UploadedFile/useGetFile.ts
  src/api/utils/createQueryKey.ts
  src/components/Tag/Tag.tsx
  src/components/UploadedFileTab/FileCategory/Category.tsx
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/interfaces.ts
  src/components/UploadedFileTab/style.ts
  src/pages/MyPage/MyPage.tsx
Labels: features

#89 Feature/request list component
  src/api/hooks/Request.tsx/useGetRequest.ts
  src/api/utils/createQueryKey.ts
  src/components/RequestList/Request.tsx
  src/components/RequestList/index.ts
  src/components/RequestList/interfaces.ts
  src/components/RequestList/style.ts
  src/pages/MyPage/MyPage.tsx
Labels: features, style

#90 Features/myrequest component
  src/api/hooks/MyRequest/useGetMyRequest.ts
  src/api/utils/createQueryKey.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/MyRequest/MyRequestList/MyRequestList.tsx
  src/components/MyRequest/MyRequestList/index.ts
  src/components/MyRequest/MyRequestList/interfaces.ts
  src/components/MyRequest/MyRequestList/style.ts
  src/components/MyRequest/index.ts
  src/components/MyRequest/interfaces.ts
  src/components/MyRequest/style.ts
  src/components/UploadedFileTab/style.ts
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
Labels: features, style

#91 Features/master login
  package.json
  src/api/utils/cookies.ts
  src/pages/Login/Login.tsx
  src/pages/Login/hooks/useLogin.ts
  src/pages/Login/styles.ts
  yarn.lock
Labels: features

#94 Feature/card component
  src/api/hooks/Card/GetCardInfo.ts
  src/api/utils/createQueryKey.ts
  src/components/Card/Card.tsx
  src/components/Card/style.ts
  src/components/MyRequest/MyRequest.tsx
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
Labels: features, style

#95 [DESIGN] : 🎨 유저 조회&생성 페이지 UI 구현
  src/pages/Business/Business.tsx
Labels: style

#99 Feature/vacation component #96
  src/api/hooks/Vacation/useGetVacation.ts
  src/api/hooks/Vacation/usePutDecision.ts
  src/api/utils/createQueryKey.ts
  src/assets/folderIcon.svg
  src/components/Card/Card.tsx
  src/components/RequestList/style.ts
  src/components/Tag/style.ts
  src/components/UploadedFileTab/style.ts
  src/components/VacationTab/Vacation/Vacation.tsx
  src/components/VacationTab/Vacation/interfaces.ts
  src/components/VacationTab/Vacation/style.ts
  src/components/VacationTab/VacationTab.tsx
  src/components/VacationTab/style.ts
  src/constants/colors.ts
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
Labels: features, style

#104 Features/file upload
  src/assets/Icons/FolderIcon.tsx
  src/constants/colors.ts
Labels: bug, style

#110 Features/modal component portal issue #109
  src/components/Modal/Modal.tsx
  src/components/Modal/interfaces.ts
  src/components/Modal/styles.ts
Labels: features, style

#112 Style/my main page style
  src/api/hooks/Request.tsx/useGetRequest.ts
  src/components/Board/Board.tsx
  src/components/Board/style.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedTitle.tsx
  src/components/Feed/style.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/MyRequest/MyRequestList/MyRequestList.tsx
  src/components/MyRequest/MyRequestList/interfaces.ts
  src/components/MyRequest/MyRequestList/style.ts
  src/components/MyRequest/style.ts
  src/components/RequestList/Request.tsx
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/RequestList/RequestedOne/index.ts
  src/components/RequestList/RequestedOne/interfaces.ts
  src/components/RequestList/RequestedOne/style.ts
  src/components/RequestList/style.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/Tags/Tags.tsx
  src/components/Tag/Tags/interfaces.ts
  src/components/Tag/Tags/style.ts
  src/components/Tag/interfaces.ts
  src/components/Tag/style.ts
  src/components/UploadedFileTab/FileCategory/Category.tsx
  src/components/UploadedFileTab/FileCategory/index.ts
  src/components/UploadedFileTab/FileCategory/interfaces.ts
  src/components/UploadedFileTab/FileCategory/style.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/components/UploadedFileTab/UploadedOne/index.ts
  src/components/UploadedFileTab/UploadedOne/interfaces.ts
  src/components/UploadedFileTab/UploadedOne/style.ts
  src/components/UploadedFileTab/UplodedFile/UploadedFile.tsx
  src/components/UploadedFileTab/UplodedFile/index.ts
  src/components/UploadedFileTab/UplodedFile/interfaces.ts
  src/components/UploadedFileTab/UplodedFile/style.ts
  src/components/UploadedFileTab/style.ts
  src/components/VacationTab/Vacation/Vacation.tsx
  src/components/VacationTab/Vacation/style.ts
  src/components/VacationTab/VacationTab.tsx
  src/components/VacationTab/style.ts
  src/hooks/common/useInput.ts
  src/pages/Manager/Manager.tsx
Labels: style

#113 Features/file upload
  src/api/hooks/Main/usePostschedule.ts
  src/assets/ReadMe.text
  src/assets/folderIcon.svg
  src/assets/temp.tsx
  src/components/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/DocumentForm/commonInterface.ts
  src/components/DocumentForm/commonStyles.ts
  src/components/FileUpload/FileUpload.tsx
  src/components/FileUpload/styles.ts
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/SubMain.tsx
Labels: features

#117 [DESIGN] : 🎨 Icon add
  src/assets/Icons/BusinessIcon.tsx
  src/assets/Icons/CalendarIcon.tsx
  src/assets/Icons/TagIcon.tsx
  src/assets/Icons/interfaces.ts
Labels: features

#118 Style/my main page style
  src/api/hooks/Request.tsx/useGetRequestDetail.ts
  src/api/utils/createQueryKey.ts
  src/components/Board/style.ts
  src/components/Card/Card.tsx
  src/components/Card/style.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/style.ts
  src/components/Feed/Feed.tsx
  src/components/Feed/FeedTitle.tsx
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/style.ts
  src/components/Feed/interfaces.ts
  src/components/Feed/style.ts
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/RequestList/RequestedOne/style.ts
  src/components/VacationTab/Vacation/Vacation.tsx
  src/constants/colors.ts
  src/hooks/common/useInput.ts
  src/pages/Manager/Manager.tsx
  src/pages/Manager/styles.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/styles.ts
Labels: style

#120 Features/file upload
  src/assets/Icons/BusinessIcon.tsx
  src/assets/Icons/CalendarIcon.tsx
  src/assets/Icons/TagIcon.tsx
  src/components/DocumentForm/ReportFormat/ReportFormat.tsx
  src/components/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/DocumentForm/commonInterface.ts
  src/components/DocumentForm/commonStyles.ts
  src/components/HashTag/HashTag.tsx
  src/components/HashTag/styles.ts
  src/pages/Main/Main.tsx
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodayScheduels/TodaySchedules.tsx
  src/pages/SubMain/TodayScheduels/styles.ts
  src/pages/SubMain/interfaces.ts
  src/pages/SubMain/utils.ts
  src/shared/GlobalStyle.tsx
Labels: features

#127 Features/uploaded file/modal
  src/api/hooks/Request.tsx/useGetRequestDetail.ts
  src/api/hooks/Request/useGetRequest.ts
  src/api/hooks/Request/useGetRequestDetail.ts
  src/api/hooks/Tag/useGetTag.ts
  src/api/hooks/UploadedFile/useGetFile.ts
  src/api/hooks/UploadedFile/useGetUploadedDetail.ts
  src/api/utils/createQueryKey.ts
  src/assets/Icons/CalendarIcon.tsx
  src/assets/Icons/VacationMeerkat.tsx
  src/components/Board/Board.tsx
  src/components/Board/style.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Feed.tsx
  src/components/RequestList/Request.tsx
  src/components/RequestList/RequestDetail/RequestDetail.tsx
  src/components/RequestList/RequestDetail/index.ts
  src/components/RequestList/RequestDetail/interfaces.ts
  src/components/RequestList/RequestDetail/style.ts
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/RequestList/RequestedOne/style.ts
  src/components/RequestList/interfaces.ts
  src/components/Tag/Tag.tsx
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/UploadedDetail/index.ts
  src/components/UploadedFileTab/UploadedDetail/interfaces.ts
  src/components/UploadedFileTab/UploadedDetail/style.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/components/UploadedFileTab/UploadedOne/interfaces.ts
  src/components/UploadedFileTab/UploadedOne/style.ts
  src/components/UploadedFileTab/interfaces.ts
  src/components/VacationTab/Vacation/style.ts
  src/components/VacationTab/VacationTab.tsx
  src/components/VacationTab/style.ts
  src/pages/Manager/Manager.tsx
  src/pages/Manager/styles.ts
  src/pages/MyPage/MyPage.tsx
Labels: features

#129 [FEAT] : ⚙️ assets에 svg파일 추가
  src/assets/Meerkat/ManagerHead.tsx
  src/assets/Meerkat/MeerkatHead4.tsx
  src/assets/Meerkat/SignupHello.tsx
  src/assets/Meerkat/SignupMeerkat.tsx
  src/assets/Meerkat/VacationMeerkat.tsx
  src/assets/Meerkat/WaitVacation.tsx
  src/assets/Meerkat/WorkingMeerkat.tsx
  src/pages/Manager/Manager.tsx
Labels: features

#130 Features/question box add
  package.json
  src/api/hooks/Main/usePostschedule.ts
  src/components/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/DocumentForm/VacationFormat/VacationFormat.tsx
  yarn.lock
Labels: features

#132 Features/user login
  src/pages/Login/Login.tsx
  src/pages/Login/hooks/useAdminLogin.ts
  src/pages/Login/hooks/useLogin.tsx
  src/pages/Login/hooks/useRePassword.ts
Labels: bug, features

#134 Features/signup fix
  src/pages/MasterSignup/MasterSignup.tsx
  src/pages/MasterSignup/hooks/useCompanyNumCheck.ts
  src/pages/MasterSignup/hooks/useSignup.ts
Labels: features

#139 Styles/login page
  src/assets/Meerkat/ManagerHead.tsx
  src/assets/Meerkat/MeerkatHead4.tsx
  src/assets/Meerkat/SignupHello.tsx
  src/assets/Meerkat/SignupMeerkat.tsx
  src/assets/Meerkat/VacationMeerkat.tsx
  src/assets/Meerkat/WaitVacation.tsx
  src/assets/Meerkat/WorkingMeerkat.tsx
  src/components/Button/Button.tsx
  src/components/Button/interfaces.ts
  src/components/Button/styles.ts
  src/components/Inputs/Input/MaxInput.tsx
  src/components/Inputs/Input/interfaces.ts
  src/components/Inputs/Input/style.ts
  src/pages/Login/Login.tsx
  src/pages/Login/styles.ts
Labels: style, fix

#141 Fix/page routing
  package.json
  src/assets/images/home/main2.jpg
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/hooks/useAdminLogin.ts
  src/pages/Login/hooks/useLogin.tsx
  src/pages/MasterSignup/hooks/useSignup.ts
  src/shared/Router.tsx
  tsconfig.json
  yarn.lock
Labels: style, fix

#143 Features/navigate tab
  src/api/hooks/Main/useGetMain.ts
  src/assets/Meerkat/ChangeSchedule.tsx
  src/assets/Meerkat/ChangeVacation.tsx
  src/components/Card/Card.tsx
  src/components/Card/style.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/interfaces.ts
  src/components/Feed/Category/style.ts
  src/components/Feed/FeedTitle.tsx
  src/components/Feed/interfaces.ts
  src/components/Feed/style.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonInterface.ts
  src/pages/Main/Main.tsx
  src/pages/Main/styles.ts
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/utils.ts
Labels: features

#147 Style/add svg #146
  src/assets/Icons/CalendarIcon.tsx
  src/assets/Icons/File.tsx
  src/assets/Icons/Person.tsx
  src/assets/images/OneWeekCalendar.jpg
  src/components/AuthRequest/AuthRequest.tsx
  src/components/AuthRequest/index.ts
  src/components/AuthRequest/style.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/MyRequest/MyRequestList/MyRequestList.tsx
  src/components/OneWeekCalendar/OneWeekCalendar.tsx
  src/components/OneWeekCalendar/style.ts
  src/components/RequestList/Request.tsx
  src/components/Tag/Tag.tsx
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/components/VacationTab/VacationTab.tsx
  src/pages/Manager/Manager.tsx
  src/pages/Manager/styles.ts
  src/pages/MyPage/MyPage.tsx
Labels: style

#148 알람창 변경 / 취소버튼 제작
  src/App.tsx
  src/api/hooks/Main/useTabContext.tsx
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/FeedTitle.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonInterface.ts
  src/pages/Main/Main.tsx
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/utils.ts
  src/shared/Router.tsx
  tsconfig.json
Labels: features

#149 Styles/signup page
  src/assets/Meerkat/SignupHello.tsx
  src/assets/Meerkat/SignupMeerkat.tsx
  src/components/Button/interfaces.ts
  src/components/Button/styles.ts
  src/components/Inputs/ButtonInput/ButtonInput.tsx
  src/components/Inputs/ButtonInput/interfaces.ts
  src/components/Inputs/ButtonInput/style.ts
  src/components/Inputs/Input/interfaces.ts
  src/components/Inputs/Input/style.ts
  src/pages/Login/Login.tsx
  src/pages/MasterSignup/MasterSignup.tsx
  src/pages/MasterSignup/hooks/DaumAddressAPI.tsx
  src/pages/MasterSignup/styles.ts
Labels: features, style

#152 Styles/business page
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/interfaces.ts
  src/components/Inputs/ButtonInput/ButtonInput.tsx
  src/components/Inputs/ButtonInput/interfaces.ts
  src/components/Inputs/ButtonInput/style.ts
  src/components/Inputs/Input/MaxInput.tsx
  src/pages/Business/Business.tsx
  src/pages/Business/CreateUser.css
  src/pages/Business/CreateUser.tsx
  src/pages/Business/styles.ts
Labels: style🎨, RE-FACTORING♻️

#154 Features/Ceo-card-Page-scroll #151
  src/api/hooks/UploadedFile/useGetUploadedDetail.ts
  src/components/Card/Card.tsx
  src/components/MyRequest/MyRequestList/MyRequestList.tsx
  src/components/RequestList/Request.tsx
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/Tag/Tag.tsx
  src/components/Tag/Tags/Tags.tsx
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/pages/Manager/Manager.tsx
  src/pages/Manager/styles.ts
  src/pages/MyPage/styles.ts
Labels: features⚙️, style🎨

#155 Features/not found page
  src/assets/images/NotFound.jpg
  src/pages/NotFound/NotFound.tsx
  src/pages/NotFound/index.ts
  src/shared/Router.tsx
Labels: features⚙️

#156 Features/qa popup add
  src/api/hooks/Main/usePostschedule.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/commonInterface.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/pages/Main/Main.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodayScheduels/TodaySchedules.tsx
  src/pages/SubMain/TodayScheduels/styles.ts
  src/pages/SubMain/interfaces.ts
  src/pages/SubMain/utils.ts
Labels: features⚙️

#159 Features/qa popup add
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/usePostVacation.ts
  src/api/hooks/Main/usePostschedule.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/pages/Main/Main.tsx
  src/pages/SubMain/TodayScheduels/TodaySchedules.tsx
Labels: bug🐛

#169 Server API <---> Calendar Type 간 프로퍼티 명 통일
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/usePostVacation.ts
  src/api/hooks/Main/usePostschedule.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonInterface.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/components/OneWeekCalendar/OneWeekCalendar.tsx
  src/pages/Main/Main.tsx
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodayScheduels/TodaySchedules.tsx
  src/pages/SubMain/interfaces.ts
  src/pages/SubMain/utils.ts
Labels: RE-FACTORING♻️

#170 로그인, 회원가입 페이지 RESTful 규칙을 준수하도록 URI 수정
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/hooks/useAdminLogin.ts
  src/pages/Login/hooks/useLogin.tsx
  src/pages/Login/hooks/useRePassword.ts
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
  src/pages/MasterSignup/hooks/useSignup.ts
Labels: RE-FACTORING♻️

#171 API 테이블 대규모 변경에 따른 리팩토링
  src/api/hooks/Feed/useDeleteCategory.ts
  src/api/hooks/Feed/useDeleteFeed.ts
  src/api/hooks/Feed/useGetFeed.ts
  src/api/hooks/Feed/usePostCategory.ts
  src/api/hooks/Feed/usePostTodo.ts
  src/api/hooks/MyRequest/useGetMyRequest.ts
  src/api/hooks/Request/useGetRequest.ts
  src/api/hooks/Request/useGetRequestDetail.ts
  src/api/hooks/Tag/useGetTag.ts
  src/api/hooks/UploadedFile/useGetFile.ts
  src/api/hooks/Vacation/useGetVacation.ts
  src/api/hooks/Vacation/usePutDecision.ts
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Category/interfaces.ts
  src/components/Feed/Category/style.ts
  src/components/Feed/Todo/AddTodo.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Feed/Todo/interfaces.ts
  src/components/Feed/Todo/style.ts
  src/components/Feed/interfaces.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/MyRequest/MyRequestList/MyRequestList.tsx
  src/components/MyRequest/MyRequestList/interfaces.ts
  src/components/MyRequest/interfaces.ts
  src/components/RequestList/Request.tsx
  src/components/RequestList/RequestDetail/RequestDetail.tsx
  src/components/RequestList/RequestDetail/interfaces.ts
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/RequestList/RequestedOne/interfaces.ts
  src/components/RequestList/interfaces.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/Tags/Tags.tsx
  src/components/Tag/Tags/interfaces.ts
  src/components/Tag/Tags/style.ts
  src/components/Tag/interfaces.ts
  src/components/UploadedFileTab/UploadedDetail/UploadedDetail.tsx
  src/components/UploadedFileTab/UploadedDetail/interfaces.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/components/UploadedFileTab/UploadedOne/interfaces.ts
  src/components/UploadedFileTab/interfaces.ts
  src/components/VacationTab/Vacation/Vacation.tsx
  src/components/VacationTab/Vacation/interfaces.ts
  src/components/VacationTab/VacationTab.tsx
  src/components/VacationTab/interfaces.ts
Labels: RE-FACTORING♻️

#177 Features/mini calendar
  src/api/hooks/Weekly/useGetWeeklyInfo.ts
  src/api/utils/createQueryKey.ts
  src/components/Main/CustomCalendar/CustomCalendar.tsx
  src/components/Main/CustomCalendar/Weekday/Weekday.tsx
  src/components/Main/CustomCalendar/Weekday/inferfaces.ts
  src/components/Main/CustomCalendar/Weekday/styles.ts
  src/components/Main/CustomCalendar/interfaces.ts
  src/components/Main/CustomCalendar/styles.ts
  src/components/OneWeekCalendar/OneWeekCalendar.tsx
Labels: features⚙️, RE-FACTORING♻️

#173 Refactor/page board
  src/components/AuthRequest/AuthRequest.tsx
  src/components/AuthRequest/style.ts
  src/components/Board/Board.tsx
  src/components/Board/style.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/MyRequest/style.ts
  src/components/RequestList/Request.tsx
  src/components/RequestList/style.ts
  src/components/Tag/Tag.tsx
  src/components/Tag/style.ts
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/UploadedFileTab/style.ts
  src/components/VacationTab/VacationTab.tsx
  src/components/VacationTab/style.ts
  src/hooks/common/useThrottleCallback.ts
Labels: RE-FACTORING♻️

#176 Features/auth request
  src/api/hooks/Request/useDecideRequest.ts
  src/api/hooks/Request/useGetRequest.ts
  src/api/hooks/Request/useGetRequestDetail.ts
  src/components/AuthRequest/AuthRequest.tsx
  src/components/AuthRequest/index.ts
  src/components/AuthRequest/style.ts
  src/components/RequestList/Request.tsx
  src/components/RequestList/RequestDetail/RequestDetail.tsx
  src/components/RequestList/RequestDetail/style.ts
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/RequestList/interfaces.ts
  src/pages/Manager/Manager.tsx
Labels: features⚙️

#179 공용 컴포넌트 재구축 및 로그인 페이지 리팩토링
  package.json
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/index.ts
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Atoms/Dropdown/index.ts
  src/components/Atoms/Dropdown/interfaces.ts
  src/components/Atoms/Dropdown/styles.ts
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/index.ts
  src/components/Atoms/Input/style.ts
  src/components/Atoms/Label/CustomLabel.tsx
  src/components/Atoms/Label/index.ts
  src/components/Atoms/Modal/CustomModal.tsx
  src/components/Atoms/Modal/index.ts
  src/components/Atoms/Modal/styles.ts
  src/components/Button/Button.tsx
  src/components/Button/index.ts
  src/components/Button/interfaces.ts
  src/components/Button/styles.ts
  src/components/Dropdown/Dropdown copy.tsx
  src/components/Dropdown/DropdownPortal.ts
  src/components/Dropdown/index.ts
  src/components/Inputs/ButtonInput/ButtonInput.tsx
  src/components/Inputs/ButtonInput/index.ts
  src/components/Inputs/ButtonInput/interfaces.ts
  src/components/Inputs/ButtonInput/style.ts
  src/components/Inputs/Input/MaxInput.tsx
  src/components/Inputs/Input/index.ts
  src/components/Inputs/Input/interfaces.ts
  src/components/Inputs/Input/style.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Modal/index.ts
  src/components/Modal/interfaces.ts
  src/components/Modal/styles.ts
  src/components/RequestList/RequestedOne/RequestedOne.tsx
  src/components/UploadedFileTab/UploadedOne/UploadedOne.tsx
  src/pages/Business/Business.tsx
  src/pages/Business/CreateUser.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/components/AdminLoginForm.tsx
  src/pages/Login/components/UserLoginForm.tsx
  src/pages/Login/hooks/useAdminLogin.ts
  src/pages/Login/hooks/useLogin.ts
  src/pages/Login/hooks/useLogin.tsx
  src/pages/Login/styles.ts
  src/pages/MasterSignup/MasterSignup.tsx
  src/pages/MasterSignup/interfaces.ts
  src/pages/SubMain/Detail/Detail.tsx
  src/shared/Router.tsx
  yarn.lock
Labels: RE-FACTORING♻️

#181 Features/card info modify
  src/api/hooks/Card/useGetCardDetail.ts
  src/api/hooks/Card/useGetCardInfo.ts
  src/api/hooks/Card/usePatchDetail.ts
  src/api/utils/createQueryKey.ts
  src/assets/Meerkat/ProfileEmployee.tsx
  src/assets/Meerkat/ProfileManager.tsx
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/style.ts
  src/components/Atoms/Modal/styles.ts
  src/components/Card/Card.tsx
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Card/CardDetail/index.ts
  src/components/Card/CardDetail/style.ts
  src/components/Card/interfaces.ts
  src/components/Card/style.ts
  src/components/Main/CustomCalendar/CustomCalendar.tsx
  src/components/OneWeekCalendar/OneWeekCalendar.tsx
  src/hooks/common/useInput.ts
  src/pages/SubMain/SubMain.tsx
Labels: features⚙️, style🎨

#182 Features/add report
  package.json
  src/App.tsx
  src/api/hooks/Main/usePostMeetingReport.ts
  src/api/hooks/Main/usePostReport.ts
  src/assets/Meerkat/ChangeSchedule.tsx
  src/assets/Meerkat/ChangeVacation.tsx
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Atoms/Dropdown/styles.ts
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/style.ts
  src/components/Atoms/Modal/CustomModal.tsx
  src/components/Feed/Category/AddCategory.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/FeedTitle.tsx
  src/components/Main/CustomCalendar/CustomCalendar.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/commonInterface.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/Main/Modal/ReportModal/styles.ts
  src/pages/Main/Main.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/subMain.css
  src/states/ReadMe.md
  src/states/recoilCalendarState.ts
  src/states/recoilClickEventState.ts
  src/states/recoilReportState.ts
  src/states/recoilTabState.ts
  yarn.lock
Labels: features⚙️

#185 Features/mypage vacationstatus
  src/api/hooks/Vacation/useGetVacationStatus.ts
  src/api/utils/createQueryKey.ts
  src/assets/Meerkat/VacationMeerkat.tsx
  src/assets/Meerkat/WaitVacation.tsx
  src/assets/Meerkat/WaitingVacation.tsx
  src/assets/Meerkat/WorkingMeerkat.tsx
  src/components/VacationStatus/VacationStatus.tsx
  src/components/VacationStatus/index.ts
  src/components/VacationStatus/style.ts
  src/pages/Manager/Manager.tsx
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/styles.ts
Labels: features⚙️

#187 Refactoring/infinite scroll #186
  src/api/hooks/MyRequest/useGetMyRequest.ts
  src/api/hooks/Request/useGetRequest.ts
  src/api/hooks/Tag/useGetTag.ts
  src/api/hooks/UploadedFile/useGetFile.ts
  src/api/hooks/Vacation/useGetVacation.ts
  src/components/MyRequest/MyRequest.tsx
  src/components/RequestList/Request.tsx
  src/components/Tag/Tag.tsx
  src/components/UploadedFileTab/UploadedFileTab.tsx
  src/components/VacationTab/VacationTab.tsx
  src/hooks/common/useInfiniteQueryHook.ts
  src/pages/SubMain/SubMain.tsx
  src/shared/Router.tsx
Labels: RE-FACTORING♻️

#189 최적화 & Main Page Bug Fix
  package.json
  src/api/hooks/Main/useGetTeamInfo.ts
  src/api/hooks/Main/useMoveScroll.ts
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Dropdown/Dropdown.tsx
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Card/Card.tsx
  src/components/Card/CardDetail/CardDetail.tsx
  src/components/Feed/Category/CategoryBox.tsx
  src/components/Feed/Feed.tsx
  src/components/Feed/Todo/TodoBox.tsx
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/commonStyles.ts
  src/components/Main/DocumentForm/components/FileUpload/FileUpload.tsx
  src/components/Main/DocumentForm/components/FileUpload/styles.ts
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/DocumentForm/components/HashTag/styles.ts
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/Main/Modal/ReportModal/styles.ts
  src/components/MyRequest/MyRequestList/MyRequestList.tsx
  src/components/VacationTab/Vacation/Vacation.tsx
  src/pages/Main/Main.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Header/Header.tsx
  src/pages/SubMain/Header/styles.ts
  src/pages/SubMain/SubMain.tsx
  src/pages/SubMain/TodayScheduels/TodaySchedules.tsx
  src/pages/Write/Write.tsx
  src/pages/Write/index.ts
  src/pages/Write/styles.ts
  src/styles/GlobalStyle.tsx
  yarn.lock
Labels: bug🐛, RE-FACTORING♻️

#191 Refactoring/master signup page
  package.json
  src/assets/Meerkat/SignupHello.tsx
  src/assets/Meerkat/SignupMeerkat.tsx
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/style.ts
  src/components/Atoms/Label/CustomLabel.tsx
  src/components/Atoms/Wrapper_Column/Wrapper_Column.tsx
  src/components/Atoms/Wrapper_Column/index.ts
  src/components/Atoms/Wrapper_Row/Wrapper_Row.tsx
  src/components/Atoms/Wrapper_Row/index.ts
  src/pages/MasterSignup/MasterSignup.tsx
  src/pages/MasterSignup/components/SignupForm.tsx
  src/pages/MasterSignup/hooks/DaumAddressAPI.tsx
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
  src/pages/MasterSignup/hooks/useCompanyNumCheck.ts
  src/pages/MasterSignup/hooks/usePasswordCheck.ts
  src/pages/MasterSignup/hooks/useSignup.ts
  src/pages/MasterSignup/interfaces.ts
  src/pages/MasterSignup/styles.ts
  src/styles/colors.ts
Labels: RE-FACTORING♻️

#194 Features/home page
  package.json
  public/favicon.ico
  public/favicon_meer.ico
  public/index.html
  src/api/hooks/Main/useGetMain.ts
  src/api/hooks/Main/useGetTeamInfo.ts
  src/api/hooks/Main/usePostMeetingReport.ts
  src/api/hooks/Main/usePostReport.ts
  src/api/hooks/Main/usePostschedule.ts
  src/assets/Icons/HeaderLogo.tsx
  src/assets/images/NotFound.jpg
  src/assets/images/home/main1.jpg
  src/assets/images/home/main2.jpg
  src/assets/images/home/main3.jpg
  src/assets/images/home/main4.jpg
  src/assets/images/home/main5.jpg
  src/assets/images/home/main6.jpg
  src/components/Main/CustomCalendar/CustomCalendar.tsx
  src/components/Main/CustomCalendar/styles.ts
  src/components/Main/DocumentForm/ScheduleFormat/ScheduleFormat.tsx
  src/components/Main/DocumentForm/VacationFormat/VacationFormat.tsx
  src/components/Main/DocumentForm/components/HashTag/HashTag.tsx
  src/components/Main/Modal/ReportModal/ReportModal.tsx
  src/components/OneWeekCalendar/OneWeekCalendar.tsx
  src/pages/Business/Business.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/hooks/useLogin.ts
  src/pages/Main/Main.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/NotFound/styles.ts
  src/pages/SubMain/Detail/Detail.tsx
  src/pages/SubMain/Detail/index.ts
  src/pages/SubMain/Detail/styles.ts
  src/pages/SubMain/SubMain.tsx
Labels: bug🐛, features⚙️

#196 Refactoring/business page
  public/index.html
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/style.ts
  src/pages/Business/Business.tsx
  src/pages/Business/CreateUser.css
  src/pages/Business/CreateUser.tsx
  src/pages/Business/business.css
  src/pages/Business/components/CreateUser.tsx
  src/pages/Business/components/DetailUser.tsx
  src/pages/Business/components/ViewUser.tsx
  src/pages/Business/hooks/useGetUser.ts
  src/pages/Business/hooks/useSignup.ts
  src/pages/Business/hooks/useUserIdValidation.ts
  src/pages/Business/interfaces.ts
  src/pages/Business/styles.ts
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
Labels: RE-FACTORING♻️

#197 유저 테스트를 위한 배포(비즈니스 페이지 추가 수정)
  public/index.html
  src/components/Atoms/Button/CustomButton.tsx
  src/components/Atoms/Button/style.ts
  src/components/Atoms/Input/CustomInput.tsx
  src/components/Atoms/Input/style.ts
  src/pages/Business/Business.tsx
  src/pages/Business/CreateUser.css
  src/pages/Business/CreateUser.tsx
  src/pages/Business/business.css
  src/pages/Business/components/CreateUser.tsx
  src/pages/Business/components/DetailUser.tsx
  src/pages/Business/components/ViewUser.tsx
  src/pages/Business/hooks/useGetUser.ts
  src/pages/Business/hooks/useSignup.ts
  src/pages/Business/hooks/useUserIdValidation.ts
  src/pages/Business/interfaces.ts
  src/pages/Business/styles.ts
  src/pages/MasterSignup/hooks/useCompanyIdValidation.ts
Labels: deploy🚀
